---
                                                            # Playbook to manage user accounts and ensure SSH access

- name: Manage user accounts and SSH access
  hosts: databases
  become: yes
  vars:
    users:
      - username: user1
        state: present
      - username: user2
        state: absent

  tasks:
    - name: Ensure users are present or absent
      user:
        name: username
        state: present
      notify: Reload SSH                                   # The Reload SSH handler is triggered only if changes are made to the user accounts or SSH configuration, ensuring efficient management and reducing unnecessary reloads.

    - name: Ensure SSH access for existing users
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'AllowUsers username'
      notify: Reload SSH                                   # The Reload SSH handler is triggered only if changes are made to the user accounts or SSH configuration, ensuring efficient management and reducing unnecessary reloads.

  handlers:
    - name: Reload SSH
      service:
        name: sshd
        state: reloaded

