---
                                                                          # Installing Httpd on webservers and Mariadb/MySQL on databases in a single playbook
- name: Install httpd
  hosts: webservers
  become: yes
  tasks:

    - name: Installing httpd
      yum:
        name: httpd
        state: present
        when:
          - ansible_facts['nodename'] == "webservers"                      # Using ansible conditions to execute the task on the specific hosts group named "webservers"
          - name: Start services
            services:
              name: httpd
              state: started
              enabled: yes

- name: Install Mariadb/MySQL
  hosts: databases
  become: yes
  tasks:

    - name: Install Mariadb/MySQL
      yum:
        name: mysql-server / mariadb-server
        state: present
        when: ansible_facts['nodename] == "databases"                      # Using ansible conditions to execute the task on the specific hosts group named "databases" 
    - name: Start service
      service:
        name: mysqld
        state: started
        enabled: yes
